# Generated by Django 3.2.6 on 2021-08-12 00:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 8, 12, 0, 48, 28, 329272, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
